CREATE TABLE SYSTEM.CDM_PROFILE_TIMEMEASUREMENT
(
  TIMEMEASUREMENT_ID INT PRIMARY KEY NOT NULL,
  MEASURED_ID INT NOT NULL,
  MULTICONTEXT_ID INT,
  TIMESTAMP VARCHAR(50)  DEFAULT 0 NOT NULL,
  DURATION VARCHAR(50)  DEFAULT 0
);
CREATE SEQUENCE TIMEMEASUREMENT_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE SYSTEM.CDM_PROFILE_MEASURED
(
    MEASURED_ID INT PRIMARY KEY NOT NULL,
    NAME VARCHAR(100) ,
    CLASS VARCHAR(100) NOT NULL,
    METHOD VARCHAR(100)  NOT NULL
);
CREATE SEQUENCE MEASURED_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE SYSTEM.CDM_PROFILE_MULTICONTEXT
(
    MULTICONTEXT_ID INT PRIMARY KEY NOT NULL,
    START_TIME VARCHAR (50) NOT NULL,
    END_TIME VARCHAR (50) NOT NULL
);
CREATE SEQUENCE MULTICONTEXT_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
