CREATE TABLE CDM_PROFILE_TIMEMEASUREMENT
(
  TIMEMEASUREMENT_ID INT PRIMARY KEY NOT NULL,
  PROCEDURE_ID INT NOT NULL ,
  MULTICONTEXT_ID INT,
  TIMESTAMP timestamp with time zone NOT NULL,
  DURATION VARCHAR(50)  DEFAULT 0
);
CREATE SEQUENCE TIMEMEASUREMENT_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE CDM_PROFILE_PROCEDURE
(
  PROCEDURE_ID INT PRIMARY KEY NOT NULL,
  NAME VARCHAR(100) ,
  CLASS VARCHAR(100) NOT NULL,
  METHOD VARCHAR(100),
  CONSTRAINT uniqueness UNIQUE (CLASS,METHOD)
);
CREATE SEQUENCE PROCEDURE_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE CDM_PROFILE_MULTICONTEXT
(
  MULTICONTEXT_ID INT PRIMARY KEY NOT NULL,
  START_TIME timestamp with time zone NOT NULL,
  END_TIME timestamp with time zone NOT NULL
);
CREATE SEQUENCE MULTICONTEXT_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE CDM_PROFILE_LAYOUT
(
  NAME VARCHAR (100) PRIMARY KEY NOT NULL,
  JSON CLOB NOT NULL
);