drop table CDM_PROFILE_TIMEMEASUREMENT cascade constraints;
drop table CDM_PROFILE_PROCEDURE cascade constraints;
drop table CDM_PROFILE_MULTICONTEXT cascade constraints;

drop sequence TIMEMEASUREMENT_SEQ;
drop sequence PROCEDURE_SEQ;
drop sequence MULTICONTEXT_SEQ;

DROP INDEX timeindex;
DROP INDEX procedureindex;

DECLARE jobno NUMBER;
BEGIN
  SELECT JOB INTO jobno FROM SYS.DBA_JOBS WHERE WHAT='DELETE FROM SYSTEM.CDM_PROFILE_MULTICONTEXT WHERE MULTICONTEXT_ID = (SELECT MULTICONTEXT_ID FROM SYSTEM.CDM_PROFILE_TIMEMEASUREMENT WHERE TIMESTAMP < SYSDATE - 15); DELETE FROM SYSTEM.CDM_PROFILE_TIMEMEASUREMENT WHERE TIMESTAMP < SYSDATE - 15;';
  dbms_job.remove(jobno);
END;